name: TecStock
description: "Sistema de Gerenciamento de Oficina"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  cpf_cnpj_validator: ^2.0.0
  table_calendar: ^3.0.0
  flutter_localizations:
    sdk: flutter
  printing: ^5.14.2
  pdf: ^3.11.3
  google_fonts: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
